name: BDchat
main: org.theglicks.bukkit.BDchat.BDchat
version: 3.1
author: StevenMG and Addicted_24_7
website: http://goo.gl/zpQV67
commands:
    cc:
        description: Change which chat channel you talk in
        usage: /cc (channel)
        aliases: ch
    bdchat:
        description: Main command for BDchat
        usage: /bdchat